apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tb.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector: { matchLabels: { app: {{ include "tb.name" . }} } }
  template:
    metadata:
      labels: { app: {{ include "tb.name" . }} }
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      serviceAccountName: {{ include "tb.serviceAccountName" . }}
      containers:
        - name: tb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources: {{- toYaml .Values.resources | nindent 12 }}
          env: {{- toYaml .Values.env | nindent 12 }}
          args: ["--nats={{ .Values.nats.url }}"]
