apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability-agents.fullname" . }}-otel
  labels:
    {{- include "observability-agents.labels" . | nindent 4 }}
data:
  collector.yaml: |
    {{- .Values.otelCollector.config | nindent 4 }}
