apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability-agents.fullname" . }}-prometheus-agent
  labels:
    {{- include "observability-agents.labels" . | nindent 4 }}
data:
  prometheus-agent.yaml: |
    {{- .Values.prometheusAgent.config | nindent 4 }}
