apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability-agents.fullname" . }}-otel
  labels:
    {{- include "observability-agents.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "observability-agents.fullname" . }}-otel
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
