apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "observability-agents.fullname" . }}-prometheus-agent
  labels:
    {{- include "observability-agents.labels" . | nindent 4 }}
  {{- with .Values.prometheusAgent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "observability-agents.fullname" . }}-promtail
  labels:
    {{- include "observability-agents.labels" . | nindent 4 }}
  {{- with .Values.promtail.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "observability-agents.fullname" . }}-otel
  labels:
    {{- include "observability-agents.labels" . | nindent 4 }}
  {{- with .Values.otelCollector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
