apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: euc1-bff
  namespace: argocd
spec:
  project: trading-platform
  source:
    repoURL: https://github.com/example/aws-trading-platform.git
    targetRevision: main
    path: k8s/charts/bff
    helm:
      releaseName: bff
      values: |
        image:
          tag: v0.1.1
        secrets:
          nats:
            name: trading-nats
            key: url
  destination:
    server: https://kubernetes.default.svc
    namespace: trading-bff
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
