apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: euc1-nats
  namespace: argocd
spec:
  project: trading-platform
  source:
    repoURL: https://github.com/example/aws-trading-platform.git
    targetRevision: main
    path: k8s/charts/nats-jetstream
    helm:
      releaseName: trading-nats
  destination:
    server: https://kubernetes.default.svc
    namespace: jetstream
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
